### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by dhcole** [cutting-room-floor/tilemill-reference-layer#5]
Now that this is going to be more generic, we should have a less specific name. @aibram, what do you think?

**Comment by ansis** [comment]
What about tilemill-basemap or tilemill-reference-layer?

**Comment by dhcole** [comment]
I like tilemill-reference-layer. @willwhite?

**Comment by willwhite** [comment]
Makes sense and I like it.

**Comment by springmeyer** [comment]
done in https://github.com/mapbox/tilemill-mapbox-streets/commit/e519dbaf389483a12343ce50a266bd2e2ff50781 and will be merged into master as part of #4.
