### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by dhcole** [cutting-room-floor/tilemill-reference-layer#7]
@springmeyer I just pushed an [update to this project](https://github.com/mapbox/tilemill-reference-layer/pull/6). Can you update it on npm? I think you're the only maintainer currently.

**Comment by springmeyer** [comment]
@dhcole - quite odd that I ended up as the only `owner`. This is fixed now, so please go ahead and publish if you like.

**Comment by springmeyer** [comment]
done, closing.
